### ISSUE TITLE
Error parsing req.body parameter when using as express module

### ISSUE THREAD

**Issue by fsi2000** [PopovMP/dbil#1] opened 2024-04-15 17:39 UTC
Get error "[ERROR] [db-api :: dbAction] cannot parse parameter: query" when using as express module.
argText is already of type object - this causes JSON.parse to return an error.

Quick-fix in ./node_modules/@popovmp/dbil/lib/api.js

```
      let argObj = null;
      const argText = req.body[param] || "{}";
      if (typeof argText === "object") {
        argObj = argText;
      } else {
        argObj = JSON.parse(argText);
      }

```

**Comment by PopovMP** [comment] 2024-04-21 05:25
Thank you for the report!

The issue is fixed in v4.8.1

**Closed as completed** 2024-08-21 04:19 UTC
